name: 'styleguide'
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pycodestyle
        uses: ankitvgupta/pycodestyle-action@master
        with:
          arguments:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRECOMMAND_MESSAGE: Style errors detected. Consider running `autopep8 --in-place --aggressive <filename>`.
